### ISSUE TITLE
run c++ main_yolo.cpp error

### ISSUE THREAD

**Issue by masommao** [hpc203/yolov5-dnn-cpp-python#6]
OpenCV(4.0.0) Error: Requested object was not found (Blob 363 not found in const blobs) in cv::dnn::dnn4_v20180917::ONNXImporter::getBlob, file c:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 272

**Comment by hpc203** [comment]
opencv版本要升级一下，最好在4.4及其以上的版本

**Comment by masommao** [comment]
niiiioopkkkmkmmmkbvfuhfdutoeuyhhycb mmio。--    发自新浪邮箱客户端
在 2月21日 11:21，hpc203 ***@***.***> 写道：


opencv版本要升级一下，最好在4.4及其以上的版本



&mdash;
